name: Python application

on:
  push:
    branches: [ "main" ]

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - run: ls -la
      - run: pwd
      - run: touch gitA
      - name: List

  test:
     runs-on: ubuntu-latest

     steps:
       - run: ls -la
       - run: pwd
       - run: touch gitA
       - name: List
       - run: ls
       - run: ls

