name: Python application

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: lsb -la
      - run: pwd
      - run: touch gitA
      - name: List
        run: ls
